# Generated by Django 4.2 on 2023-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_user_account_balance_user_active_investment_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
