# Generated by Django 4.2 on 2023-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='customers/documents/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='customers/documents/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='customers/documents/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='customers/documents/')),
                ('proof_of_address', models.ImageField(blank=True, null=True, upload_to='customers/documents/')),
            ],
        ),
    ]
