# Generated by Django 4.2 on 2023-04-17 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ROI', 'Return on Investment'), ('NUB', 'New User Bonus')], default='DEPOSIT', max_length=20)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='P', max_length=5)),
                ('channel', models.CharField(choices=[('BTC', 'Bitcoin'), ('WIR', 'Wire'), ('PPL', 'Paypal'), ('CSH', 'Cash App'), ('ACB', 'Added to Account Balance')], max_length=5)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
