# Generated by Django 4.2 on 2023-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0004_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gift_bonus',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='investment_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_amount',
            field=models.IntegerField(default=0),
        ),
    ]
