# Generated by Django 4.2 on 2023-05-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0008_creditcard_owner_alter_creditcard_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='owner',
            new_name='user',
        ),
    ]
