# Generated by Django 4.2 on 2023-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0009_rename_owner_creditcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proof_of_address',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
