# Generated by Django 4.2.1 on 2023-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0010_alter_document_id_back_alter_document_id_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='document',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='document',
            name='proof_of_address',
        ),
        migrations.RemoveField(
            model_name='document',
            name='selfie',
        ),
        migrations.AddField(
            model_name='document',
            name='kyc_id',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
