# Generated by Django 4.2.1 on 2023-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0011_remove_document_id_back_remove_document_id_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kyc_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
