# Generated by Django 4.2.1 on 2023-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttb_backend', '0012_alter_document_kyc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kyc_id',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
